### ISSUE TITLE
incompatible with chef 12.19.33 ?

### ISSUE THREAD

**Issue by caboteria** [chef/minitest-chef-handler#92]
Our kitchen tests started failing when we upgraded to chef 12.19.33.

test code:
```ruby
describe 'recipe::system::apache' do
  it 'Installs the Apache web server' do
    package('httpd').must_be_installed
  end
end
```

test error:
>         1) Error:
>       recipe::system::apache#test_0001_Installs the Apache web server:
>       NoMethodError: undefined method `arch' for Chef::Resource::Package
>           /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.33/lib/chef/resource.rb:1377:in `method_missing'
>           /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.33/lib/chef/provider/package/yum.rb:517:in `safe_arch_array'
>           /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.33/lib/chef/provider/package/yum.rb:220:in `block in query_yum_cache'
>           /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.33/lib/chef/provider/package/yum.rb:216:in `each'
>           /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.33/lib/chef/provider/package/yum.rb:216:in `each_with_index'
>           /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.33/lib/chef/provider/package/yum.rb:216:in `query_yum_cache'
>           /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.33/lib/chef/provider/package/yum.rb:92:in `load_current_resource'
They pass when I use chef 12.18.31 instead.

**Comment by rpunt** [comment]
Same issue here; identical failure mode, same workaround (12.18.31).

**Comment by cgunasree08** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
